from parkinglot import Parking_lot

if __name__ == '__main__':
    parkinglot = Parking_lot()
    parkinglot.create_parking_space(5)
    parkinglot.parking_of_vehicle("WB-01-AK-3452", "Black")
    parkinglot.parking_of_vehicle("WB-01-BK-3822", "Black")
    parkinglot.parking_of_vehicle("WB-01-CK-3322", "Blue")
    parkinglot.parking_of_vehicle("WB-01-DK-3842", "Black")
    parkinglot.parking_of_vehicle("WB-01-EK-3825", "Blue")
    parkinglot.parking_of_vehicle("WB-01-EK-3815", "Blue")
    print("slot no by reg no :")
    print(parkinglot.get_slot_no_by_registration_no("WB-01-AK-3452"))
    print(parkinglot.get_slot_no_by_registration_no("WB-01-CK-3322"))
    print(parkinglot.get_slot_no_by_registration_no("WB-01-BK-3822"))
    print(parkinglot.get_slot_no_by_registration_no("WB-01-DK-3842"))
    print(parkinglot.get_slot_no_by_registration_no("WB-01-EK-3825"))
    print(parkinglot.get_slot_no_by_registration_no("WB-01-EK-3815"))
    print("list of all car in parking")
    parkinglot.show_all_parked_cars()
    parkinglot.leave_parking(3)
    parkinglot.parking_of_vehicle("WB-01-EK-3815", "Blue")
    print("list of all car in parking after changes")
    parkinglot.show_all_parked_cars()
    print("slot no of black cars")
    print(parkinglot.get_slot_no_of_all_car_by_colour("Black"))
    print("slot no of blue cars")
    print(parkinglot.get_slot_no_of_all_car_by_colour("Blue"))
    print("reg no of black car")
    print(parkinglot.get_regno_of_all_car_by_colour("Black"))
    print("reg no of blue cars")
    print(parkinglot.get_regno_of_all_car_by_colour("Blue"))
